### ISSUE TITLE
January 20, 2020 | Code-Review : The Poodles

### ISSUE THREAD

**Issue by sz16900** [jabichris/smashing-magazine-clone#2]
Good Job on starting this project with great style. Also, splitting the team to work on different sections of the project is a GREAT idea.
- One quick suggestion: start by commenting on your code so that the team knows what some things are doing and where those sections are.

**Comment by Flakster** [comment]
Hi Chris, nice work so far. It will be good to switch the order in which you link your css style files to reflect the logical process of first reset the styles for all browsers and then add your styles.

**Comment by Meltrust** [comment]
Great work so far! Nothing else to add for now.
